-- MySQL Script generated by MySQL Workbench
-- Sat Jun  5 08:43:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `productcol` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`province` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `province` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `province_id` INT NOT NULL,
  `region` VARCHAR(120) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `province_idx` (`province_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 340
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`sub_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`sub_region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `province_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  `sub_region` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `region_idx` (`region_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1708
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`cumtomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cumtomer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `phone_number` VARCHAR(45) NULL,
  `province_id` INT NULL,
  `region_id` INT NULL,
  `sug_region_id` INT NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `sub_region_idx` (`sug_region_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `id` INT NOT NULL,
  `customer_id` INT NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `cutomer_idx` (`customer_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NULL,
  `product_id` INT NULL,
  `order_id` INT NULL,
  `qty` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_idx` (`order_id` ASC) VISIBLE)
ENGINE = InnoDB;

USE `default_schema` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
